/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.zero.orzprofiler.profiler.router;

public class Constants {

  public static final String LOCAL_HOST = "host";

  public static final String TYPE = "type";

  public static final String RECVWINSIZE = "recvwinsize";

  public static final String TIMEOUT = "TIMEOUT";

  public static final String SUBSCRIBER = "subscriber";

}
