/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.zero.profiler.router;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ExReason implements org.apache.thrift.TEnum {
  SERVICE_UNAVAILABLE(100),
  INVALID_USERPWD(200),
  NOTFOUNT_BROKER(201),
  UNAUTHORIED_CATEGORY(202);

  private final int value;

  private ExReason(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ExReason findByValue(int value) { 
    switch (value) {
      case 100:
        return SERVICE_UNAVAILABLE;
      case 200:
        return INVALID_USERPWD;
      case 201:
        return NOTFOUNT_BROKER;
      case 202:
        return UNAUTHORIED_CATEGORY;
      default:
        return null;
    }
  }
}
